---
# bbackup configuration for a remote backup

repo-path: ssh://backupserver.example.com/./borg-repo-name
# source-directories:  # defaults to home directory
#   - dir1
#   - dir2
#   - etc.

borg-path: /usr/local/bin/borg-1-1-8

mac-whitelist:
  - 01:23:45:67:89:0a
  - 12:34:56:78:90:ab
